/*!
 * Copyright (C) 2005-2012 Gekko Emulator
 *
 * \file    version.h
 * \author  ShizZy <shizzy247@gmail.com>
 * \date    2012-03-04
 * \brief   Version of the project. Do not edit this file.
 *
 * \section LICENSE
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details at
 * http://www.gnu.org/copyleft/gpl.html
 *
 * Official project repository can be found at:
 * http://code.google.com/p/gekko-gc-emu/
 */

#ifndef COMMON_VERSION_
#define COMMON_VERSION_

#define GEKKO_VERSION "0.31-" GEKKO_SVN_REV
#define GEKKO_SVN_REV "dirty"

#endif // COMMON_VERSION