//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDS_DBG_STR_START               1
#define IDS_LVCOL01                     2
#define IDS_LVCOL02                     3
#define IDS_LVCOL03                     4
#define IDS_LVCOL04                     5
#define IDS_LVCOL05                     6
#define IDS_LVCOL06                     7
#define IDR_FMENU                       101
#define IDR_MENU                        101
#define IDD_MEMVIEW                     103
#define IDD_ABOUT                       104
#define IDD_GEKKODEBUG                  112
#define IDD_MEMVIEW__                   113
#define IDD_DISVIEW                     115
#define IDD_DIALOG2                     121
#define IDD_GPRVIEW                     121
#define IDD_REGSVIEW                    121
#define IDD_IRQSTAT                     124
#define IDD_ABOUT_GEKKO                 127
#define IDD_SYSVIEW                     128
#define IDI_JAPAN                       129
#define IDI_USA                         130
#define IDD_VIDEO_CONFIG                132
#define IDD_JOYPAD_CONFIG               133
#define IDI_1GEKKO                      145
#define IDI_ZBRKPT                      150
#define IDC_CUSTOM                      1001
#define IDC_SEARCH                      1003
#define IDC_CONFIG_FULLSCREEN           1003
#define IDC_FIND                        1004
#define IDC_CONFIG_WINDOW_RESOLUTION    1004
#define IDC_CONFIG_FULLSCREEN_RESOLUTION 1005
#define IDC_CONFIG_SHADER_MODE          1006
#define IDS_R0                          1007
#define IDC_CHECK4                      1007
#define IDS_R1                          1008
#define IDC_CHECK5                      1008
#define IDS_R2                          1009
#define IDC_CONFIG_OK                   1009
#define IDS_R3                          1010
#define IDC_CONFIG_CANCEL               1010
#define IDS_R4                          1011
#define IDC_CHECK6                      1011
#define IDS_R5                          1012
#define IDC_CONFIG_APPLY                1012
#define IDS_R6                          1013
#define IDC_CONFIG_FORCE_ALPHA          1013
#define IDS_R7                          1014
#define IDC_BUTTON2                     1014
#define IDC_CONFIG_FORCE_ALPHA2         1014
#define IDC_CONFIG_DUMP_TEXTURES        1014
#define IDS_R8                          1015
#define IDS_R9                          1016
#define IDS_R10                         1017
#define IDC_CHECK8                      1017
#define IDS_R11                         1018
#define IDC_CONFIG_WIREFRAME            1018
#define IDS_R12                         1019
#define IDC_CHECK10                     1019
#define IDS_R13                         1020
#define IDS_R14                         1021
#define IDS_R15                         1022
#define IDS_R16                         1023
#define IDS_GBR                         1023
#define IDS_IRQAI                       1023
#define IDS_R17                         1024
#define IDS_PR                          1024
#define IDS_MSR                         1024
#define IDS_IRQEXI                      1024
#define IDS_R18                         1025
#define IDS_SSR                         1025
#define IDS_IRQSI                       1025
#define IDS_R19                         1026
#define IDS_SPC                         1026
#define IDS_IRQDI                       1026
#define IDS_R20                         1027
#define IDS_VBR                         1027
#define IDS_IRQRSW                      1027
#define IDS_R21                         1028
#define IDS_SGR                         1028
#define IDS_IRQERROR                    1028
#define IDS_R22                         1029
#define IDS_DBR                         1029
#define IDS_IRQAI2                      1029
#define IDC_JOYPAD_DEFAULT              1029
#define IDS_R23                         1030
#define IDS_B0                          1030
#define IDS_IRQEXI2                     1030
#define IDC_JOYPAD_CLEAR                1030
#define IDS_R24                         1031
#define IDS_B1                          1031
#define IDS_IRQSI2                      1031
#define IDC_JOYPAD_ANALOGUP             1031
#define IDS_R25                         1032
#define IDS_B2                          1032
#define IDS_IRQDI2                      1032
#define IDC_JOYPAD_ANALOGDOWN           1032
#define IDS_R26                         1033
#define IDS_B3                          1033
#define IDS_IRQRSW2                     1033
#define IDC_JOYPAD_ANALOGRIGHT          1033
#define IDS_R27                         1034
#define IDS_B4                          1034
#define IDS_IRQERROR2                   1034
#define IDC_JOYPAD_ANALOGLEFT           1034
#define IDS_R28                         1035
#define IDS_B5                          1035
#define IDC_JOYPAD_CUP                  1035
#define IDS_R29                         1036
#define IDS_B6                          1036
#define IDC_JOYPAD_CDOWN                1036
#define IDS_R30                         1037
#define IDS_B7                          1037
#define IDS_R31                         1038
#define IDB_STEP                        1038
#define IDC_JOYPAD_CLEFT                1038
#define IDC_MEMSEL                      1039
#define IDB_GENERAL_PURPOSE_REGISTERS   1039
#define IDC_JOYPAD_START                1039
#define IDB_CONTROLLER                  1039
#define IDS_SR_S                        1040
#define IDB_STEP3                       1040
#define IDB_STEPOUTT                    1040
#define IDC_JOYPAD_L                    1040
#define IDC_DISASMVIEW                  1041
#define IDB_STEP4                       1041
#define IDB_MOVECURSORTOO               1041
#define IDC_JOYPAD_R                    1041
#define IDS_SR_Q                        1042
#define IDB_SYSTEM_REGISTERS            1042
#define IDC_JOYPAD_Z                    1042
#define IDS_SR_M                        1043
#define IDC_JOYPAD_DUP                  1043
#define IDS_SR_BL                       1044
#define IDC_JOYPAD_DDOWN                1044
#define IDS_MACH                        1045
#define IDB_PAUSE                       1045
#define IDC_JOYPAD_DRIGHT               1045
#define IDS_MACL                        1046
#define IDB_GENERAL_PURPOSE_REGISTERS3  1046
#define IDB_REGISTERS_VIEW              1046
#define IDC_JOYPAD_DLEFT                1046
#define IDS_SR_IMASK                    1047
#define IDB_GENERAL_PURPOSE_REGISTERS4  1047
#define IDB_INTERRUPT_STATUS            1047
#define IDC_JOYPAD_A                    1047
#define IDS_PC                          1048
#define IDC_JOYPAD_B                    1048
#define IDS_FPSCR                       1049
#define IDB_UNPAUSE                     1049
#define IDC_JOYPAD_X                    1049
#define IDS_FPUL                        1050
#define IDC_JOYPAD_Y                    1050
#define IDS_SR_FD                       1051
#define IDC_JOYPAD_OK                   1051
#define IDS_SR_RB                       1052
#define IDC_JOYPAD_CANCEL               1052
#define IDS_SR_MD                       1053
#define IDC_JOYPAD_CANCEL2              1053
#define IDC_JOYPAD_APPLY                1053
#define IDS_SR_T                        1054
#define IDC_JOYPAD_PLUGGED              1055
#define IDC_JOYPAD_STATIC_ANALOGUP      1056
#define IDC_ADDR                        1057
#define IDC_JOYPAD_STATIC_ANALOGDOWN    1057
#define IDB_GOTO                        1058
#define IDC_JOYPAD_STATIC_ANALOGRIGHT   1058
#define IDS_FR0                         1059
#define IDC_JOYPAD_STATIC_ANALOGLEFT    1059
#define IDS_FR1                         1060
#define IDC_JOYPAD_STATIC_CUP           1060
#define IDS_FR2                         1061
#define IDC_JOYPAD_STATIC_CDOWN         1061
#define IDS_FR3                         1062
#define IDC_JOYPAD_STATIC_CRIGHT        1062
#define IDS_FR4                         1063
#define IDC_JOYPAD_STATIC_CLEFT         1063
#define IDS_FR5                         1064
#define IDC_JOYPAD_STATIC_START         1064
#define IDS_FR6                         1065
#define IDC_JOYPAD_STATIC_L             1065
#define IDS_FR7                         1066
#define IDC_JOYPAD_STATIC_R             1066
#define IDS_FR8                         1067
#define IDC_JOYPAD_STATIC_Z             1067
#define IDS_FR9                         1068
#define IDC_JOYPAD_STATIC_DUP           1068
#define IDS_FR10                        1069
#define IDC_JOYPAD_STATIC_DDOWN         1069
#define IDS_FR11                        1070
#define IDC_JOYPAD_STATIC_DRIGHT        1070
#define IDS_FR12                        1071
#define IDC_JOYPAD_STATIC_DLEFT         1071
#define IDS_FR13                        1072
#define IDC_JOYPAD_STATIC_A             1072
#define IDS_FR14                        1073
#define IDC_JOYPAD_STATIC_B             1073
#define IDS_FR15                        1074
#define IDC_JOYPAD_STATIC_X             1074
#define IDC_JOYPAD_STATIC_Y             1075
#define IDC_VIEWSEL                     1076
#define IDC_JOYPAD_CRIGHT               1076
#define IDB_START                       1078
#define IDC_VIEW                        1078
#define IDB_SKIP                        1079
#define IDS_CCR                         1080
#define IDB_SETPC                       1080
#define IDS_QACR0                       1081
#define IDS_LR                          1081
#define IDB_RUNPCTOO                    1081
#define IDS_QACR1                       1082
#define IDS_CR                          1082
#define IDS_MMUCR                       1083
#define IDS_CRT                         1083
#define IDS_CTR                         1083
#define IDS_FPUREGS                     1084
#define IDC_FPSEL1                      1085
#define IDS_XER                         1085
#define IDC_FPSEL2                      1086
#define IDS_IC                          1086
#define IDC_FPSEL3                      1087
#define IDB_START2                      1088
#define IDB_STEPOV                      1089
#define IDC_JOYPAD_CONTROLLER1          1089
#define IDC_CHECK3                      1090
#define IDB_STEPOUT                     1090
#define IDB_STEPOV2                     1090
#define IDB_RUNPC                       1090
#define IDB_RUNPCTO                     1090
#define IDC_JOYPAD_CONTROLLER2          1090
#define IDC_EDIT1                       1091
#define IDC_EDITPC                      1091
#define IDC_JOYPAD_CONTROLLER3          1091
#define IDC_XF                          1092
#define IDB_SKIPPCTOO                   1092
#define IDC_JOYPAD_DEFAULT7             1092
#define IDC_JOYPAD_CONTROLLER4          1092
#define IDS_CallStack                   1093
#define IDB_SETCURSOR                   1093
#define IDC_ARM7INFO                    1094
#define IDC_CALLSTACK                   1095
#define IDC_BPADDR                      1096
#define IDC_FUNCTIONLIST                1096
#define IDC_ADDREMOVEBP                 1097
#define IDB_ADDREMOVEBP                 1097
#define IDS_IRQRSWST                    1105
#define IDS_IRQHSP                      1106
#define IDS_IRQDEBUG                    1107
#define IDS_IRQCP                       1108
#define IDS_IRQPEFINISH                 1109
#define IDS_IRQPETOKEN                  1110
#define IDS_IRQVI                       1111
#define IDS_IRQMEM                      1112
#define IDS_IRQDSP                      1113
#define IDS_IRQRSWST2                   1114
#define IDC_VSYNC                       1114
#define IDC_REGS_TAB                    1114
#define IDS_IRQHSP2                     1115
#define IDS_SSR0                        1115
#define IDS_SRR0                        1115
#define IDS_IRQDEBUG2                   1116
#define IDS_SSR1                        1116
#define IDS_SRR1                        1116
#define IDS_IRQCP2                      1117
#define IDS_SPRG0                       1117
#define IDS_IRQPEFINISH2                1118
#define IDS_SPRG1                       1118
#define IDS_IRQPETOKEN2                 1119
#define IDS_SPRG2                       1119
#define IDS_IRQVI2                      1120
#define IDS_SPRG3                       1120
#define IDS_IRQMEM2                     1121
#define IDS_HID0                        1121
#define IDS_IRQDSP2                     1122
#define IDS_HID1                        1122
#define IDS_IRQPENDING                  1123
#define IDS_HID2                        1123
#define IDS_IRQEXTERNAL                 1124
#define IDS_WPAR                        1124
#define IDS_IRQMSREE                    1125
#define IDS_DMAU                        1125
#define IDS_VIINT0                      1126
#define IDS_DMAL                        1126
#define IDS_DSISR                       1127
#define IDS_DAR                         1128
#define IDS_DEC                         1129
#define IDS_EAR                         1130
#define IDS_PVR                         1131
#define IDC_EVENT                       1133
#define IDC_TAB2                        1136
#define IDC_REGLBL0                     1137
#define IDC_REGLBL1                     1138
#define IDC_REGLBL2                     1139
#define IDC_REGLBL3                     1140
#define IDC_REGLBL4                     1141
#define IDC_REGLBL5                     1142
#define IDC_REGLBL6                     1143
#define IDC_REGLBL7                     1144
#define IDC_REGLBL8                     1145
#define IDC_REGLBL9                     1146
#define IDC_REGLBL10                    1147
#define IDC_REGLBL11                    1148
#define IDC_REGLBL12                    1149
#define IDC_REGLBL13                    1150
#define IDC_REGLBL14                    1151
#define IDC_REGLBL15                    1152
#define IDC_REGLBL16                    1153
#define IDC_REGLBL17                    1154
#define IDC_REGLBL18                    1155
#define IDC_REGLBL19                    1156
#define IDC_REGLBL20                    1157
#define IDC_REGLBL21                    1158
#define IDC_REGLBL22                    1159
#define IDC_REGLBL23                    1160
#define IDC_REGLBL24                    1161
#define IDC_REGLBL25                    1162
#define IDC_REGLBL26                    1163
#define IDC_REGLBL27                    1164
#define IDC_REGLBL28                    1165
#define IDC_REGLBL29                    1166
#define IDC_REGLBL30                    1167
#define IDC_REGLBL31                    1168
#define IDC_JOYPAD_GROUP                1170
#define IDC_VIDEO_DEVICE                1171
#define IDC_ABOUT_OK                    1172
#define ID_EMULATION_RESET              2323
#define IDB_STOP                        10755
#define IDC_MAIN_STATUS                 11104
#define IDD_REGGPR                      16244
#define ID_FILE_EXIT                    40001
#define ID_EXIT                         40001
#define ID_SYSTEM_START                 40003
#define ID_EMULATION_START              40003
#define ID_SYSTEM_STOP                  40004
#define ID_EMULATION_STOP               40004
#define ID_SYSTEM_RESET                 40006
#define ID_DEBUG_MEMVIEWER              40007
#define ID_DEBUG_REGVIEWER              40008
#define ID_DEBUG_DISASMVIEWER           40009
#define ID_DEBUG_PVRLISTVIEWER          40010
#define ID_DEBUG_ARMDEBUG               40011
#define ID_HELP_ABOUT                   40012
#define ID_HELP_HOWTO                   40013
#define ID_DEBUG_DEBUGGER               40014
#define ID_FILE_OPENBIN                 40019
#define ID_DEBUG_ARM7DEBUGGER           40020
#define ID_FILE_LOADELF                 40022
#define ID_FILE_LOADDOL                 40023
#define ID_FILE_BOOTIPL                 40025
#define ID_FILE_LOADMAP                 40026
#define ID_FILE_LOADGCCMAP              40026
#define ID_FILE_LOADCWMAP               40028
#define ID_BETAC2006SHIZZYAPRENTICETHAKIS 40029
#define ID_OPTIONS_ENABLEFRAMEBUFFER    40031
#define ID_OPTIONS_ENABLESYSTEMCALL     40032
#define ID_OPTIONS_AUTOSYNC             40036
#define ID_OPTIONS_AUDIO                40037
#define ID_OPTIONS_INPUT                40038
#define ID_OPTIONS_VIDEO_ABOUT          40040
#define ID_OPTIONS_VIDEO_DOLPHINONLY    40041
#define ID_DEBUG_OPTIONS                40042
#define ID_Menu                         40044
#define ID_DEBUG_OPTIONS_DUMPCRC        40045
#define ID_FILE_BOOTAPPLOADER           40046
#define ID_OPTIONS_DISABLEHLE           40047
#define ID_OPTIONS_DISABLEINIPATCHES    40048
#define ID_DEBUG_DUMPOPCODE0            40049
#define ID_DEBUG_PAUSEONUNKNOWNOPCODE   40050
#define ID_DEBUG_DUMPRAM                40051
#define ID_FILE_CHOOSEROMDIRECTORY      40052
#define ID_FILE_REFRESHROMLIST          40053
#define ID_FILE_ROMINFO                 40054
#define ID_OPTIONS_CONFIGUREAUDIOPLUGIN 40055
#define ID_OPTIONS_CONFIGUREINPUTPLUGIN 40056
#define ID_OPTIONS_CONFIGUREDVDPLUGIN   40057
#define ID_OPTIONS_SETTINGS             40058
#define ID_OPTIONS_FULLSCREEN           40059
#define ID_HELP_CONTENTS                40060
#define ID_DEBUGOPTIONS_DUMPBLOCKREADS  40062
#define ID_SYSTEM_DYNAREC               40063
#define ID_DEBUG_COMPARECORES           40064
#define ID_COMPARECORES_STARTSERVER     40065
#define ID_COMPARECORES_STARTCLIENT     40066
#define ID_DEBUGOPTIONS_DISPLAYFRAMERATE 40067
#define ID_OPTIONS_SETMEMORYCARDIMAGE   40068
#define ID_CONFIGURECONTROLLERPLUGIN_PORT1 40069
#define ID_CONFIGURECONTROLLERPLUGIN_PORT2 40070
#define ID_CONFIGURECONTROLLERPLUGIN_PORT3 40071
#define ID_CONFIGURECONTROLLERPLUGIN_PORT4 40072
#define ID_OPTIONS_VIDEO_SETTINGS       40074
#define ID_OPTIONS_JOYPAD_SETTINGS      40075
#define ID_HELP_GETLATESTGAMELIST       40079
#define ID_HELP_HOMEPAGE                40080
#define ID_EMULATION_AUTOSTART          40083
#define ID_DEBUGVIEW                    62156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40084
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
